### ISSUE TITLE
我想切换默认端口，但是发生了错误

### ISSUE THREAD

**Issue by h88782481** [FatPaper-1874/fatpaper-site#11]
![{03B1BA8A-9B60-468A-921A-81D30E8C5C7E}](https://github.com/user-attachments/assets/d0eb02b9-d286-4081-ae71-07ada6457ea2)
如图，配置文件里的端口均已更改

**Comment by h88782481** [comment]
已经找到出错点

**Comment by lasky141414** [comment]
您好，您是怎么解决的，可以说一下么
