### ISSUE TITLE
服务端没启动成功

### ISSUE THREAD

**Issue by ttofTnT** [FatPaper-1874/fatpaper-site#12]
# 环境
m1 pro 16 G  

# 启动方式
`quick-docker-start.sh`

# 问题
monopoly-server 这个服务没有启动
<img width="532" alt="image" src="https://github.com/user-attachments/assets/8bf19564-94ec-46ee-85fd-b782f5c6b382">
<img width="898" alt="image" src="https://github.com/user-attachments/assets/68474969-3fcc-40b4-8e6d-b9faf4ddc3a4">

我手动restart 之后
<img width="347" alt="image" src="https://github.com/user-attachments/assets/debd2630-1538-43fd-bf99-fe7ccc3229b5">
<img width="772" alt="image" src="https://github.com/user-attachments/assets/2c54f13e-6e53-4bd8-9fd3-ed0101ba180b">
仍然显示链接失败
![image](https://github.com/user-attachments/assets/434eca9a-481a-4385-81d8-c5084741e5bc)

**Comment by PURE281** [comment]
docker没有试过，本地运行一共需要启动五个服务，看上面好像只运行了4个，可以检查一下哪个没有启动成功

**Comment by FatPaper-1874** [comment]
是我之前修改了默认端口的问题, 已回复到原来版本, 请拉取最新的代码。
这个问题已经在 commit [ced3988d9fdaaa9467bc2124ca4d3fb92dcabfa3](https://github.com/FatPaper-1874/fatpaper-monopoly/commit/ced3988d9fdaaa9467bc2124ca4d3fb92dcabfa3) 中修复。

**Comment by ttofTnT** [comment]
👌已解决
