### ISSUE TITLE
[docker部署相关]服务启动成功，但无法注册账号，也无法游客登陆

### ISSUE THREAD

**Issue by Zhurp2020** [FatPaper-1874/fatpaper-site#15]
服务部署成功，都起来了，没有修改过配置，mysql也操作过了
![image](https://github.com/user-attachments/assets/fcc2516d-a2d9-4ae5-a8f0-6d2485556637)
浏览器能访问登录页面
![image](https://github.com/user-attachments/assets/4de7156c-3625-4eb3-84b6-810757a3ffb0)
但是点击右边无事发生，页面空白，如图
![image](https://github.com/user-attachments/assets/e70974b6-2ef1-421d-81ff-ad81355c8866)
点击左边进入注册，点击注册无事发生，返回登陆则提示用户不存在
刷新后，仍如上图空白页面

**Comment by Zhurp2020** [comment]
补充一下，linux系统，腾讯云服务器，80-85端口均已放开

**Comment by l1m3syc** [comment]
同样的问题 mark一下  好像是cors跨域问题 加载不了
https://monopoly-static-1304992673.cos.ap-guangzhou.myqcloud.com/dice.glb这个文件

**Comment by FatPaper-1874** [comment]
同样问题请参考：[issues#17](https://github.com/FatPaper-1874/fatpaper-monopoly/issues/17)
