### ISSUE TITLE
对象存储出现CORS问题，无法加载相关资源

### ISSUE THREAD

**Issue by laishouchao** [FatPaper-1874/fatpaper-site#17]
对象存储出现CORS问题，无法加载相关资源

https://fatpaper-1304992673.cos.ap-guangzhou.myqcloud.com/monopoly/static/dice.glb

**Comment by FatPaper-1874** [comment]
由于下行流量费用的问题，限制了除127.0.0.1和localhost以外的ip或域名的访问本人的COS资源。
这个[commit](https://github.com/FatPaper-1874/fatpaper-monopoly/commit/cf56014a1b7d36bf45a4bf2f29d35111445fdb8b)修改了基础资源（骰子，字体）的访问路径，可以正确访问；但动态资源（模型、图片等）仍会被限制，可以下载资源然后在管理端进行替换；
